name: isttt24

channels:
  - conda-forge
  - pyviz
  - anaconda
dependencies:
  - python=3.7
  - jupyterlab=2.1.2
  - ipykernel=5.2.1
  - black=19.10b0
  - pytest=5.4.1
  - ipywidgets=7.5.1
  - hvplot=0.5.2
  - numpy=1.18.4
  - bokeh=2.0.1
  - pylint=2.4.4
  - pandas=1.0.3
  - ipympl=0.5.6
  - networkx=2.4
  - selenium=3.141.0
  - phantomjs=2.1.1
  - matplotlib=
  - seaborn=0.10.1
  - scipy=1.4.1
  - nodejs=13.13.0
  - voila=0.1.21
  - pip=20.1
  - papermill=2.1.0
  - pip:
      - https://github.com/symuvia/symupy/archive/v0.3.3.tar.gz
