name: isttt24

channels:
  - conda-forge
  - pyviz
  - anaconda
dependencies:
  - python=3.7
  - jupyterlab
  - ipykernel
  - black
  - pytest
  - ipywidgets
  - hvplot
  - numpy
  - bokeh
  - pylint
  - pandas
  - ipympl
  - networkx
  - selenium
  - phantomjs
  - matplotlib
  - seaborn
  - scipy
  - nodejs
  - voila
  - pip
  - papermill
  - pip:
      - https://github.com/symuvia/symupy/archive/v0.3.1.tar.gz
